AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template to deploy lambda function
Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: s3://sam-lambda-demo-the-lomax/7c7ae8c418274e0507ff8bb7b448f604
      Description: Demo of a lambda function
      MemorySize: 128
      Timeout: 10
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /
            Method: GET
    Metadata:
      SamResourceId: HelloFunction
